---
title: "Weekly_HSP_Report"
author: "Shuhei Iimura"
date: "2020/02/11"
output: 
  html_document:
    toc: true
    toc:_depth: 4
    toc_float: true
    df_print: "paged"
    theme: cosmo
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 12, fig.width = 12, warning = FALSE, cache = TRUE)
#セットアップチャンクの設定はこの通り #エラー警告は非表示にした #キャッシュ利用に設定
```

# 目次
このレポートでは、Weekly_HSP_Projectの分析経過を報告します。分析の構成は以下のとおりです。分析の再現性を担保するために用いたコードも記しています。

  * （1）前処理
  * （2）相関分析
  * （3）時点別のWidaman's Approach（メイン分析）
  * （4）1か月間のWidaman's Approach（下位分析）

# （1）前処理

## 1-1. ローデータの読み込み
```{r handling, include = TRUE}
#tidyverseパッケージ読み込み
library(tidyverse)

#データ読み込み
lowdata <- read_csv("lowdata_4timepoints.csv", na = c(".", ""))
lowdata$gender_T1 <- factor(lowdata$gender_T1) #性別をfactor型に変換
lowdata$gender_T2 <- factor(lowdata$gender_T2) #性別をfactor型に変換
lowdata$gender_T3 <- factor(lowdata$gender_T3) #性別をfactor型に変換
lowdata$gender_T4 <- factor(lowdata$gender_T4) #性別をfactor型に変換
head(lowdata) #先頭6行確認
names(lowdata) #変数名確認
```


## 1-2. 下位尺度得点作成
```{r subscales, include = TRUE}
data <- lowdata %>% 
  dplyr::mutate(eoe_T1 = (hsc4_T1 + hsc6_T1 + hsc8_T1 + hsc9_T1 + hsc12_T1)/5, na.rm = TRUE) %>% #EOE_T1の平均
  dplyr::mutate(lst_T1 = (hsc2_T1 + hsc11_T1)/2, na.rm = TRUE) %>% #LST_T1の平均
  dplyr::mutate(aes_T1 = (hsc5_T1 + hsc10_T1 + hsc1_T1 + hsc3_T1)/4, na.rm = TRUE) %>% #AES_T1の平均
  dplyr::mutate(hsc_T1 = (eoe_T1 + lst_T1 + aes_T1)/3, na.rm = TRUE) %>% #HSC_T1の平均
  dplyr::mutate(eoe_T2 = (hsc4_T2 + hsc6_T2 + hsc8_T2 + hsc9_T2 + hsc12_T2)/5, na.rm = TRUE) %>% #EOE_T2の平均
  dplyr::mutate(lst_T2 = (hsc2_T2 + hsc11_T2)/2, na.rm = TRUE) %>% #LST_T2の平均
  dplyr::mutate(aes_T2 = (hsc5_T2 + hsc10_T2 + hsc1_T2 + hsc3_T2)/4, na.rm = TRUE) %>% #AES_T2の平均
  dplyr::mutate(hsc_T2 = (eoe_T2 + lst_T2 + aes_T2)/3, na.rm = TRUE)  %>% #HSC_T2の平均
  dplyr::mutate(eoe_T3 = (hsc4_T3 + hsc6_T3 + hsc8_T3 + hsc9_T3 + hsc12_T3)/5, na.rm = TRUE) %>% #EOE_T3の平均
  dplyr::mutate(lst_T3 = (hsc2_T3 + hsc11_T3)/2, na.rm = TRUE) %>% #LST_T3の平均
  dplyr::mutate(aes_T3 = (hsc5_T3 + hsc10_T3 + hsc1_T3 + hsc3_T3)/4, na.rm = TRUE) %>% #AES_T3の平均
  dplyr::mutate(hsc_T3 = (eoe_T3 + lst_T3 + aes_T3)/3, na.rm = TRUE) %>% #HSC_T3の平均
  dplyr::mutate(eoe_T4 = (hsc4_T4 + hsc6_T4 + hsc8_T4 + hsc9_T4 + hsc12_T4)/5, na.rm = TRUE) %>% #EOE_T4の平均
  dplyr::mutate(lst_T4 = (hsc2_T4 + hsc11_T4)/2, na.rm = TRUE) %>% #LST_T4の平均
  dplyr::mutate(aes_T4 = (hsc5_T4 + hsc10_T4 + hsc1_T4 + hsc3_T4)/4, na.rm = TRUE) %>% #AES_T4の平均
  dplyr::mutate(hsc_T4 = (eoe_T4 + lst_T4 + aes_T4)/3, na.rm = TRUE) %>% #HSC_T4の平均
  dplyr::mutate(hsc_onemonth = (hsc_T1 + hsc_T2 + hsc_T3 + hsc_T4)/4, na.rm = TRUE) %>% #1ヵ月間のHSC平均
  dplyr::mutate(wb_T1 = (wb1_T1 + wb2_T1 + wb3_T1 + wb4_T1 + wb5_T1)/5, na.rm = TRUE) %>% #wb_T1の平均
  dplyr::mutate(wb_T2 = (wb1_T2 + wb2_T2 + wb3_T2 + wb4_T2 + wb5_T2)/5, na.rm = TRUE) %>% #wb_T2の平均
  dplyr::mutate(wb_T3 = (wb1_T3 + wb2_T3 + wb3_T3 + wb4_T3 + wb5_T3)/5, na.rm = TRUE) %>% #wb_T3の平均
  dplyr::mutate(wb_T4 = (wb1_T4 + wb2_T4 + wb3_T4 + wb4_T4 + wb5_T4)/5, na.rm = TRUE) %>% #wb_T4の平均
  dplyr::mutate(wb_onemonth = (wb_T1 + wb_T2 + wb_T3 + wb_T4)/4, na.rm = TRUE) %>% #1か月間のwb平均
  dplyr::mutate(ev_T1 = (as.numeric(ev1_T1) + as.numeric(ev2_T1))/2, na.rm = TRUE) %>% #event_T1の平均 #as.numericにしないとエラーが出る
  dplyr::mutate(ev_T2 = (as.numeric(ev1_T2) + as.numeric(ev2_T2))/2, na.rm = TRUE) %>% #event_T2の平均
  dplyr::mutate(ev_T3 = (as.numeric(ev1_T3) + as.numeric(ev2_T3))/2, na.rm = TRUE) %>% #event_T3の平均
  dplyr::mutate(ev_T4 = (as.numeric(ev1_T4) + as.numeric(ev2_T4))/2, na.rm = TRUE) %>% #event_T4の平均
  dplyr::mutate(ev_onemonth = (ev_T1 + ev_T2 + ev_T3 + ev_T4)/4, na.rm = TRUE) %>% #1か月間のev平均
  dplyr::select(-na.rm) #謎にna.rmという変数が勝手に作成されてしまうのでそれを除外

head(data) #先頭6行確認
names(data) #変数名確認
# write.csv(data, file = "data_for_analysis.csv", na = ".") #csvで書き出し
```

## 1-3. 度数分布とヒストグラム
```{r count, include = TRUE}
library(plotly)

#性別T1の度数分布とヒストグラム
gender_T1_count <- dplyr::count(data, gender_T1)
knitr::kable(gender_T1_count) #テーブル化
a <- ggplot(data = data, mapping = aes(x = gender_T1, fill = factor(gender_T1))) + geom_bar() #視覚化
ggplotly(a) #視覚化

#性別T2の度数分布とヒストグラム
gender_T2_count <- dplyr::count(data, gender_T2)
knitr::kable(gender_T2_count) #テーブル化
b <- ggplot(data = data, mapping = aes(x = gender_T2, fill = factor(gender_T2))) + geom_bar() #視覚化
ggplotly(b) #視覚化

#性別T3の度数分布とヒストグラム
gender_T3_count <- dplyr::count(data, gender_T3)
knitr::kable(gender_T3_count) #テーブル化
c <- ggplot(data = data, mapping = aes(x = gender_T3, fill = factor(gender_T3))) + geom_bar() #視覚化
ggplotly(c) #視覚化

#性別T4の度数分布とヒストグラム
gender_T4_count <- dplyr::count(data, gender_T4)
knitr::kable(gender_T4_count) #テーブル化
d <- ggplot(data = data, mapping = aes(x = gender_T4, fill = factor(gender_T4))) + geom_bar() #視覚化
ggplotly(d) #視覚化

#hsc1_T1の度数分布とヒストグラム
hsc1_T1_count <- dplyr::count(data, hsc1_T1)
knitr::kable(hsc1_T1_count) #テーブル化
e <- ggplot(data = data, mapping = aes(x = hsc1_T1, fill = factor(hsc1_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(e) #視覚化

#hsc2_T1の度数分布とヒストグラム
hsc2_T1_count <- dplyr::count(data, hsc2_T1)
knitr::kable(hsc2_T1_count) #テーブル化
f <- ggplot(data = data, mapping = aes(x = hsc2_T1, fill = factor(hsc2_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(f) #視覚化

#hsc3_T1の度数分布とヒストグラム
hsc3_T1_count <- dplyr::count(data, hsc3_T1)
knitr::kable(hsc3_T1_count) #テーブル化
g <- ggplot(data = data, mapping = aes(x = hsc3_T1, fill = factor(hsc3_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(g) #視覚化

#hsc4_T1の度数分布とヒストグラム
hsc4_T1_count <- dplyr::count(data, hsc4_T1)
knitr::kable(hsc4_T1_count) #テーブル化
h <- ggplot(data = data, mapping = aes(x = hsc4_T1, fill = factor(hsc4_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(h) #視覚化

#hsc5_T1の度数分布とヒストグラム
hsc5_T1_count <- dplyr::count(data, hsc5_T1)
knitr::kable(hsc5_T1_count) #テーブル化
i <- ggplot(data = data, mapping = aes(x = hsc5_T1, fill = factor(hsc5_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(i) #視覚化

#hsc6_T1の度数分布とヒストグラム
hsc6_T1_count <- dplyr::count(data, hsc6_T1)
knitr::kable(hsc6_T1_count) #テーブル化
j <- ggplot(data = data, mapping = aes(x = hsc6_T1, fill = factor(hsc6_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(j) #視覚化

#hsc7_T1の度数分布とヒストグラム
hsc7_T1_count <- dplyr::count(data, hsc7_T1)
knitr::kable(hsc7_T1_count) #テーブル化
k <- ggplot(data = data, mapping = aes(x = hsc7_T1, fill = factor(hsc7_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(k) #視覚化

#hsc8_T1の度数分布とヒストグラム
hsc8_T1_count <- dplyr::count(data, hsc8_T1)
knitr::kable(hsc8_T1_count) #テーブル化
l <- ggplot(data = data, mapping = aes(x = hsc8_T1, fill = factor(hsc8_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(l) #視覚化

#hsc9_T1の度数分布とヒストグラム
hsc9_T1_count <- dplyr::count(data, hsc9_T1)
knitr::kable(hsc9_T1_count) #テーブル化
m <- ggplot(data = data, mapping = aes(x = hsc9_T1, fill = factor(hsc9_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(m) #視覚化

#hsc10_T1の度数分布とヒストグラム
hsc10_T1_count <- dplyr::count(data, hsc10_T1)
knitr::kable(hsc10_T1_count) #テーブル化
n <- ggplot(data = data, mapping = aes(x = hsc10_T1, fill = factor(hsc10_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(n) #視覚化

#hsc11_T1の度数分布とヒストグラム
hsc11_T1_count <- dplyr::count(data, hsc11_T1)
knitr::kable(hsc11_T1_count) #テーブル化
o <- ggplot(data = data, mapping = aes(x = hsc11_T1, fill = factor(hsc11_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(o) #視覚化

#hsc12_T1の度数分布とヒストグラム
hsc12_T1_count <- dplyr::count(data, hsc12_T1)
knitr::kable(hsc12_T1_count) #テーブル化
p <- ggplot(data = data, mapping = aes(x = hsc12_T1, fill = factor(hsc12_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(p) #視覚化

#hsc1_T2の度数分布とヒストグラム
hsc1_T2_count <- dplyr::count(data, hsc1_T2)
knitr::kable(hsc1_T2_count) #テーブル化
q <- ggplot(data = data, mapping = aes(x = hsc1_T2, fill = factor(hsc1_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(q) #視覚化

#hsc2_T2の度数分布とヒストグラム
hsc2_T2_count <- dplyr::count(data, hsc2_T2)
knitr::kable(hsc2_T2_count) #テーブル化
r <- ggplot(data = data, mapping = aes(x = hsc2_T2, fill = factor(hsc2_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(r) #視覚化

#hsc3_T2の度数分布とヒストグラム
hsc3_T2_count <- dplyr::count(data, hsc3_T2)
knitr::kable(hsc3_T2_count) #テーブル化
s <- ggplot(data = data, mapping = aes(x = hsc3_T2, fill = factor(hsc3_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(s) #視覚化

#hsc4_T2の度数分布とヒストグラム
hsc4_T2_count <- dplyr::count(data, hsc4_T2)
knitr::kable(hsc4_T2_count) #テーブル化
t <- ggplot(data = data, mapping = aes(x = hsc4_T2, fill = factor(hsc4_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(t) #視覚化

#hsc5_T2の度数分布とヒストグラム
hsc5_T2_count <- dplyr::count(data, hsc5_T2)
knitr::kable(hsc5_T2_count) #テーブル化
u <- ggplot(data = data, mapping = aes(x = hsc5_T2, fill = factor(hsc5_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(u) #視覚化

#hsc6_T2の度数分布とヒストグラム
hsc6_T2_count <- dplyr::count(data, hsc6_T2)
knitr::kable(hsc6_T2_count) #テーブル化
v <- ggplot(data = data, mapping = aes(x = hsc6_T2, fill = factor(hsc6_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(v) #視覚化

#hsc7_T2の度数分布とヒストグラム
hsc7_T2_count <- dplyr::count(data, hsc7_T2)
knitr::kable(hsc7_T2_count) #テーブル化
w <- ggplot(data = data, mapping = aes(x = hsc7_T2, fill = factor(hsc7_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(w) #視覚化

#hsc8_T2の度数分布とヒストグラム
hsc8_T2_count <- dplyr::count(data, hsc8_T2)
knitr::kable(hsc8_T2_count) #テーブル化
neko <- ggplot(data = data, mapping = aes(x = hsc8_T2, fill = factor(hsc8_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(neko) #視覚化

#hsc9_T2の度数分布とヒストグラム
hsc9_T2_count <- dplyr::count(data, hsc9_T2)
knitr::kable(hsc9_T2_count) #テーブル化
y <- ggplot(data = data, mapping = aes(x = hsc9_T2, fill = factor(hsc9_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(y) #視覚化

#hsc10_T2の度数分布とヒストグラム
hsc10_T2_count <- dplyr::count(data, hsc10_T2)
knitr::kable(hsc10_T2_count) #テーブル化
z <- ggplot(data = data, mapping = aes(x = hsc10_T2, fill = factor(hsc10_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(z) #視覚化

#hsc11_T2の度数分布とヒストグラム
hsc11_T2_count <- dplyr::count(data, hsc11_T2)
knitr::kable(hsc11_T2_count) #テーブル化
aa <- ggplot(data = data, mapping = aes(x = hsc11_T2, fill = factor(hsc11_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(aa) #視覚化

#hsc12_T2の度数分布とヒストグラム
hsc12_T2_count <- dplyr::count(data, hsc12_T2)
knitr::kable(hsc12_T2_count) #テーブル化
bb <- ggplot(data = data, mapping = aes(x = hsc12_T2, fill = factor(hsc12_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(bb) #視覚化

#hsc1_T3の度数分布とヒストグラム
hsc1_T3_count <- dplyr::count(data, hsc1_T3)
knitr::kable(hsc1_T3_count) #テーブル化
cc <- ggplot(data = data, mapping = aes(x = hsc1_T3, fill = factor(hsc1_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(cc) #視覚化

#hsc2_T3の度数分布とヒストグラム
hsc2_T3_count <- dplyr::count(data, hsc2_T3)
knitr::kable(hsc2_T3_count) #テーブル化
dd <- ggplot(data = data, mapping = aes(x = hsc2_T3, fill = factor(hsc2_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(dd) #視覚化

#hsc3_T3の度数分布とヒストグラム
hsc3_T3_count <- dplyr::count(data, hsc3_T3)
knitr::kable(hsc3_T3_count) #テーブル化
ff <- ggplot(data = data, mapping = aes(x = hsc3_T3, fill = factor(hsc3_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(ff) #視覚化

#hsc4_T3の度数分布とヒストグラム
hsc4_T3_count <- dplyr::count(data, hsc4_T3)
knitr::kable(hsc4_T3_count) #テーブル化
gg <- ggplot(data = data, mapping = aes(x = hsc4_T3, fill = factor(hsc4_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(gg) #視覚化

#hsc5_T3の度数分布とヒストグラム
hsc5_T3_count <- dplyr::count(data, hsc5_T3)
knitr::kable(hsc5_T3_count) #テーブル化
hh <- ggplot(data = data, mapping = aes(x = hsc5_T3, fill = factor(hsc5_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(hh) #視覚化

#hsc6_T3の度数分布とヒストグラム
hsc6_T3_count <- dplyr::count(data, hsc6_T3)
knitr::kable(hsc6_T3_count) #テーブル化
ii <- ggplot(data = data, mapping = aes(x = hsc6_T3, fill = factor(hsc6_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(ii) #視覚化

#hsc7_T3の度数分布とヒストグラム
hsc7_T3_count <- dplyr::count(data, hsc7_T3)
knitr::kable(hsc7_T3_count) #テーブル化
jj <- ggplot(data = data, mapping = aes(x = hsc7_T3, fill = factor(hsc7_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(jj) #視覚化

#hsc8_T3の度数分布とヒストグラム
hsc8_T3_count <- dplyr::count(data, hsc8_T3)
knitr::kable(hsc8_T3_count) #テーブル化
kk <- ggplot(data = data, mapping = aes(x = hsc8_T3, fill = factor(hsc8_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(kk) #視覚化

#hsc9_T3の度数分布とヒストグラム
hsc9_T3_count <- dplyr::count(data, hsc9_T3)
knitr::kable(hsc9_T3_count) #テーブル化
ll <- ggplot(data = data, mapping = aes(x = hsc9_T3, fill = factor(hsc9_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(ll) #視覚化

#hsc10_T3の度数分布とヒストグラム
hsc10_T3_count <- dplyr::count(data, hsc10_T3)
knitr::kable(hsc10_T3_count) #テーブル化
dog <- ggplot(data = data, mapping = aes(x = hsc10_T3, fill = factor(hsc10_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(dog) #視覚化

#hsc11_T3の度数分布とヒストグラム
hsc11_T3_count <- dplyr::count(data, hsc11_T3)
knitr::kable(hsc11_T3_count) #テーブル化
mm <- ggplot(data = data, mapping = aes(x = hsc11_T3, fill = factor(hsc11_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(mm) #視覚化

#hsc12_T3の度数分布とヒストグラム
hsc12_T3_count <- dplyr::count(data, hsc12_T3)
knitr::kable(hsc12_T3_count) #テーブル化
nn <- ggplot(data = data, mapping = aes(x = hsc12_T3, fill = factor(hsc12_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(nn) #視覚化

#hsc1_T4の度数分布とヒストグラム
hsc1_T4_count <- dplyr::count(data, hsc1_T4)
knitr::kable(hsc1_T4_count) #テーブル化
oo <- ggplot(data = data, mapping = aes(x = hsc1_T4, fill = factor(hsc1_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(oo) #視覚化

#hsc2_T4の度数分布とヒストグラム
hsc2_T4_count <- dplyr::count(data, hsc2_T4)
knitr::kable(hsc2_T4_count) #テーブル化
pp <- ggplot(data = data, mapping = aes(x = hsc2_T4, fill = factor(hsc2_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(pp) #視覚化

#hsc3_T4の度数分布とヒストグラム
hsc3_T4_count <- dplyr::count(data, hsc3_T4)
knitr::kable(hsc3_T4_count) #テーブル化
qq <- ggplot(data = data, mapping = aes(x = hsc3_T4, fill = factor(hsc3_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(qq) #視覚化

#hsc4_T4の度数分布とヒストグラム
hsc4_T4_count <- dplyr::count(data, hsc4_T4)
knitr::kable(hsc4_T4_count) #テーブル化
rr <- ggplot(data = data, mapping = aes(x = hsc4_T4, fill = factor(hsc4_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(rr) #視覚化

#hsc5_T4の度数分布とヒストグラム
hsc5_T4_count <- dplyr::count(data, hsc5_T4)
knitr::kable(hsc5_T4_count) #テーブル化
ss <- ggplot(data = data, mapping = aes(x = hsc5_T4, fill = factor(hsc5_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(ss) #視覚化

#hsc6_T4の度数分布とヒストグラム
hsc6_T4_count <- dplyr::count(data, hsc6_T4)
knitr::kable(hsc6_T4_count) #テーブル化
inu <- ggplot(data = data, mapping = aes(x = hsc6_T4, fill = factor(hsc6_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(inu) #視覚化

#hsc7_T4の度数分布とヒストグラム
hsc7_T4_count <- dplyr::count(data, hsc7_T4)
knitr::kable(hsc7_T4_count) #テーブル化
tt <- ggplot(data = data, mapping = aes(x = hsc7_T4, fill = factor(hsc7_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(tt) #視覚化

#hsc8_T4の度数分布とヒストグラム
hsc8_T4_count <- dplyr::count(data, hsc8_T4)
knitr::kable(hsc8_T4_count) #テーブル化
vv <- ggplot(data = data, mapping = aes(x = hsc8_T4, fill = factor(hsc8_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(vv) #視覚化

#hsc9_T4の度数分布とヒストグラム
hsc9_T4_count <- dplyr::count(data, hsc9_T4)
knitr::kable(hsc9_T4_count) #テーブル化
ww <- ggplot(data = data, mapping = aes(x = hsc9_T4, fill = factor(hsc9_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(ww) #視覚化

#hsc10_T4の度数分布とヒストグラム
hsc10_T4_count <- dplyr::count(data, hsc10_T4)
knitr::kable(hsc10_T4_count) #テーブル化
kame <- ggplot(data = data, mapping = aes(x = hsc10_T4, fill = factor(hsc10_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(kame) #視覚化

#hsc11_T4の度数分布とヒストグラム
hsc11_T4_count <- dplyr::count(data, hsc11_T4)
knitr::kable(hsc11_T4_count) #テーブル化
yy <- ggplot(data = data, mapping = aes(x = hsc11_T4, fill = factor(hsc11_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(yy) #視覚化

#hsc12_T4の度数分布とヒストグラム
hsc12_T4_count <- dplyr::count(data, hsc12_T4)
knitr::kable(hsc12_T4_count) #テーブル化
zz <- ggplot(data = data, mapping = aes(x = hsc12_T4, fill = factor(hsc12_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(zz) #視覚化

#wb1_T1の度数分布とヒストグラム
wb1_T1_count <- dplyr::count(data, wb1_T1)
knitr::kable(wb1_T1_count) #テーブル化
aaa <- ggplot(data = data, mapping = aes(x = wb1_T1, fill = factor(wb1_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(aaa) #視覚化

#wb2_T1の度数分布とヒストグラム
wb2_T1_count <- dplyr::count(data, wb2_T1)
knitr::kable(wb2_T1_count) #テーブル化
bbb <- ggplot(data = data, mapping = aes(x = wb2_T1, fill = factor(wb2_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(bbb) #視覚化

#wb3_T1の度数分布とヒストグラム
wb3_T1_count <- dplyr::count(data, wb3_T1)
knitr::kable(wb3_T1_count) #テーブル化
ccc <- ggplot(data = data, mapping = aes(x = wb3_T1, fill = factor(wb3_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(ccc) #視覚化

#wb4_T1の度数分布とヒストグラム
wb4_T1_count <- dplyr::count(data, wb4_T1)
knitr::kable(wb4_T1_count) #テーブル化
ddd <- ggplot(data = data, mapping = aes(x = wb4_T1, fill = factor(wb4_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(ddd) #視覚化

#wb5_T1の度数分布とヒストグラム
wb5_T1_count <- dplyr::count(data, wb5_T1)
knitr::kable(wb5_T1_count) #テーブル化
eee <- ggplot(data = data, mapping = aes(x = wb5_T1, fill = factor(wb5_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(eee) #視覚化

#wb1_T2の度数分布とヒストグラム
wb1_T2_count <- dplyr::count(data, wb1_T2)
knitr::kable(wb1_T2_count) #テーブル化
fff <- ggplot(data = data, mapping = aes(x = wb1_T2, fill = factor(wb1_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(fff) #視覚化

#wb2_T2の度数分布とヒストグラム
wb2_T2_count <- dplyr::count(data, wb2_T2)
knitr::kable(wb2_T2_count) #テーブル化
ggg <- ggplot(data = data, mapping = aes(x = wb2_T2, fill = factor(wb2_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(ggg) #視覚化

#wb3_T2の度数分布とヒストグラム
wb3_T2_count <- dplyr::count(data, wb3_T2)
knitr::kable(wb3_T2_count) #テーブル化
hhh <- ggplot(data = data, mapping = aes(x = wb3_T2, fill = factor(wb3_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(hhh) #視覚化

#wb4_T2の度数分布とヒストグラム
wb4_T2_count <- dplyr::count(data, wb4_T2)
knitr::kable(wb4_T2_count) #テーブル化
iii <- ggplot(data = data, mapping = aes(x = wb4_T2, fill = factor(wb4_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(iii) #視覚化

#wb5_T2の度数分布とヒストグラム
wb5_T2_count <- dplyr::count(data, wb5_T2)
knitr::kable(wb5_T2_count) #テーブル化
jjj <- ggplot(data = data, mapping = aes(x = wb5_T2, fill = factor(wb5_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(jjj) #視覚化

#wb1_T3の度数分布とヒストグラム
wb1_T3_count <- dplyr::count(data, wb1_T3)
knitr::kable(wb1_T3_count) #テーブル化
kkk <- ggplot(data = data, mapping = aes(x = wb1_T3, fill = factor(wb1_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(kkk) #視覚化

#wb2_T3の度数分布とヒストグラム
wb2_T3_count <- dplyr::count(data, wb2_T3)
knitr::kable(wb2_T3_count) #テーブル化
lll <- ggplot(data = data, mapping = aes(x = wb2_T3, fill = factor(wb2_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(lll) #視覚化

#wb3_T3の度数分布とヒストグラム
wb3_T3_count <- dplyr::count(data, wb3_T3)
knitr::kable(wb1_T3_count) #テーブル化
mmm <- ggplot(data = data, mapping = aes(x = wb3_T3, fill = factor(wb3_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(mmm) #視覚化

#wb4_T3の度数分布とヒストグラム
wb4_T3_count <- dplyr::count(data, wb4_T3)
knitr::kable(wb4_T3_count) #テーブル化
nnn <- ggplot(data = data, mapping = aes(x = wb4_T3, fill = factor(wb4_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(nnn) #視覚化

#wb5_T3の度数分布とヒストグラム
wb5_T3_count <- dplyr::count(data, wb5_T3)
knitr::kable(wb5_T3_count) #テーブル化
ooo <- ggplot(data = data, mapping = aes(x = wb5_T3, fill = factor(wb5_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(ooo) #視覚化

#wb1_T4の度数分布とヒストグラム
wb1_T4_count <- dplyr::count(data, wb1_T4)
knitr::kable(wb1_T4_count) #テーブル化
ppp <- ggplot(data = data, mapping = aes(x = wb1_T4, fill = factor(wb1_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(ppp) #視覚化

#wb2_T4の度数分布とヒストグラム
wb2_T4_count <- dplyr::count(data, wb2_T4)
knitr::kable(wb2_T4_count) #テーブル化
qqq <- ggplot(data = data, mapping = aes(x = wb2_T4, fill = factor(wb2_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(qqq) #視覚化

#wb3_T4の度数分布とヒストグラム
wb3_T4_count <- dplyr::count(data, wb3_T4)
knitr::kable(wb3_T4_count) #テーブル化
rrr <- ggplot(data = data, mapping = aes(x = wb3_T4, fill = factor(wb3_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(rrr) #視覚化

#wb5_T4の度数分布とヒストグラム
wb5_T4_count <- dplyr::count(data, wb5_T4)
knitr::kable(wb5_T4_count) #テーブル化
sss <- ggplot(data = data, mapping = aes(x = wb5_T4, fill = factor(wb5_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(sss) #視覚化

#event1_T1の度数分布とヒストグラム
event1_T1_count <- dplyr::count(data, ev1_T1)
knitr::kable(event1_T1_count) #テーブル化
ttt <- ggplot(data = data, mapping = aes(x = ev1_T1, fill = factor(ev1_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(ttt) #視覚化

#event2_T1の度数分布とヒストグラム
event2_T1_count <- dplyr::count(data, ev2_T1)
knitr::kable(event2_T1_count) #テーブル化
uuu <- ggplot(data = data, mapping = aes(x = ev2_T1, fill = factor(ev2_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(uuu) #視覚化

#event1_T2の度数分布とヒストグラム
event1_T2_count <- dplyr::count(data, ev1_T2)
knitr::kable(event1_T2_count) #テーブル化
vvv <- ggplot(data = data, mapping = aes(x = ev1_T2, fill = factor(ev1_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(vvv) #視覚化

#event2_T2の度数分布とヒストグラム
event2_T2_count <- dplyr::count(data, ev2_T2)
knitr::kable(event2_T2_count) #テーブル化
www <- ggplot(data = data, mapping = aes(x = ev2_T2, fill = factor(ev2_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(www) #視覚化

#event1_T3の度数分布とヒストグラム
event1_T3_count <- dplyr::count(data, ev1_T3)
knitr::kable(event1_T3_count) #テーブル化
usagi <- ggplot(data = data, mapping = aes(x = ev1_T3, fill = factor(ev1_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(usagi) #視覚化

#event2_T3の度数分布とヒストグラム
event2_T3_count <- dplyr::count(data, ev2_T3)
knitr::kable(event2_T3_count) #テーブル化
yyy <- ggplot(data = data, mapping = aes(x = ev2_T3, fill = factor(ev2_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(yyy) #視覚化

#event1_T4の度数分布とヒストグラム
event1_T4_count <- dplyr::count(data, ev1_T4)
knitr::kable(event1_T4_count) #テーブル化
zzz <- ggplot(data = data, mapping = aes(x = ev1_T4, fill = factor(ev1_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(zzz) #視覚化

#event2_T4の度数分布とヒストグラム
event2_T4_count <- dplyr::count(data, ev2_T4)
knitr::kable(event2_T4_count) #テーブル化
aaaa <- ggplot(data = data, mapping = aes(x = ev2_T4, fill = factor(ev2_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(aaaa) #視覚化

#eoe_T1の度数分布とヒストグラム
eoe_T1_count <- dplyr::count(data, eoe_T1)
knitr::kable(eoe_T1_count) #テーブル化
bbbb <- ggplot(data = data, mapping = aes(x = eoe_T1, fill = factor(eoe_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(bbbb) #視覚化

#eoe_T2の度数分布とヒストグラム
eoe_T2_count <- dplyr::count(data, eoe_T2)
knitr::kable(eoe_T2_count) #テーブル化
cccc <- ggplot(data = data, mapping = aes(x = eoe_T2, fill = factor(eoe_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(cccc) #視覚化

#eoe_T3の度数分布とヒストグラム
eoe_T3_count <- dplyr::count(data, eoe_T3)
knitr::kable(eoe_T3_count) #テーブル化
dddd <- ggplot(data = data, mapping = aes(x = eoe_T3, fill = factor(eoe_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(dddd) #視覚化

#eoe_T4の度数分布とヒストグラム
eoe_T4_count <- dplyr::count(data, eoe_T4)
knitr::kable(eoe_T4_count) #テーブル化
eeee <- ggplot(data = data, mapping = aes(x = eoe_T4, fill = factor(eoe_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(eeee) #視覚化

#lst_T1の度数分布とヒストグラム
lst_T1_count <- dplyr::count(data, lst_T1)
knitr::kable(lst_T1_count) #テーブル化
ffff <- ggplot(data = data, mapping = aes(x = lst_T1, fill = factor(lst_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(ffff) #視覚化

#lst_T2の度数分布とヒストグラム
lst_T2_count <- dplyr::count(data, lst_T2)
knitr::kable(lst_T2_count) #テーブル化
gggg <- ggplot(data = data, mapping = aes(x = lst_T2, fill = factor(lst_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(gggg) #視覚化

#lst_T3の度数分布とヒストグラム
lst_T3_count <- dplyr::count(data, lst_T3)
knitr::kable(lst_T3_count) #テーブル化
hhhh <- ggplot(data = data, mapping = aes(x = lst_T3, fill = factor(lst_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(hhhh) #視覚化

#lst_T4の度数分布とヒストグラム
lst_T4_count <- dplyr::count(data, lst_T4)
knitr::kable(lst_T4_count) #テーブル化
iiii <- ggplot(data = data, mapping = aes(x = lst_T4, fill = factor(lst_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(iiii) #視覚化

#aes_T1の度数分布とヒストグラム
aes_T1_count <- dplyr::count(data, aes_T1)
knitr::kable(aes_T1_count) #テーブル化
jjjj <- ggplot(data = data, mapping = aes(x = aes_T1, fill = factor(aes_T1))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(jjjj) #視覚化

#aes_T2の度数分布とヒストグラム
aes_T2_count <- dplyr::count(data, aes_T2)
knitr::kable(aes_T2_count) #テーブル化
kkkk <- ggplot(data = data, mapping = aes(x = aes_T2, fill = factor(aes_T2))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(kkkk) #視覚化

#aes_T3の度数分布とヒストグラム
aes_T3_count <- dplyr::count(data, aes_T3)
knitr::kable(aes_T3_count) #テーブル化
llll <- ggplot(data = data, mapping = aes(x = aes_T3, fill = factor(aes_T3))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(llll) #視覚化

#aes_T4の度数分布とヒストグラム
aes_T4_count <- dplyr::count(data, aes_T4)
knitr::kable(aes_T4_count) #テーブル化
mmmm <- ggplot(data = data, mapping = aes(x = aes_T4, fill = factor(aes_T4))) + geom_histogram(binwidth = 1) #視覚化
ggplotly(mmmm) #視覚化

#hsc_T1の度数分布とヒストグラム
hsc_T1_count <- dplyr::count(data, hsc_T1)
knitr::kable(hsc_T1_count) #テーブル化
nnnn <- ggplot(data = data, mapping = aes(x = hsc_T1, fill = factor(hsc_T1))) + geom_histogram(binwidth = 0.1) #視覚化
ggplotly(nnnn) #視覚化

#hsc_T2の度数分布とヒストグラム
hsc_T2_count <- dplyr::count(data, hsc_T2)
knitr::kable(hsc_T2_count) #テーブル化
oooo <- ggplot(data = data, mapping = aes(x = hsc_T2, fill = factor(hsc_T2))) + geom_histogram(binwidth = 0.1) #視覚化
ggplotly(oooo) #視覚化

#hsc_T3の度数分布とヒストグラム
hsc_T3_count <- dplyr::count(data, hsc_T3)
knitr::kable(hsc_T3_count) #テーブル化
pppp <- ggplot(data = data, mapping = aes(x = hsc_T3, fill = factor(hsc_T3))) + geom_histogram(binwidth = 0.1) #視覚化
ggplotly(pppp) #視覚化

#hsc_T4の度数分布とヒストグラム
hsc_T4_count <- dplyr::count(data, hsc_T4)
knitr::kable(hsc_T4_count) #テーブル化
qqqq <- ggplot(data = data, mapping = aes(x = hsc_T4, fill = factor(hsc_T4))) + geom_histogram(binwidth = 0.1) #視覚化
ggplotly(qqqq) #視覚化

#wb_T1の度数分布とヒストグラム
wb_T1_count <- dplyr::count(data, wb_T1)
knitr::kable(wb_T1_count) #テーブル化
rrrr <- ggplot(data = data, mapping = aes(x = wb_T1, fill = factor(wb_T1))) + geom_histogram(binwidth = 0.5) #視覚化
ggplotly(rrrr) #視覚化

#wb_T2の度数分布とヒストグラム
wb_T2_count <- dplyr::count(data, wb_T2)
knitr::kable(wb_T2_count) #テーブル化
ssss <- ggplot(data = data, mapping = aes(x = wb_T2, fill = factor(wb_T2))) + geom_histogram(binwidth = 0.5) #視覚化
ggplotly(ssss) #視覚化

#wb_T3の度数分布とヒストグラム
wb_T3_count <- dplyr::count(data, wb_T3)
knitr::kable(wb_T3_count) #テーブル化
tttt <- ggplot(data = data, mapping = aes(x = wb_T3, fill = factor(wb_T3))) + geom_histogram(binwidth = 0.5) #視覚化
ggplotly(tttt) #視覚化

#wb_T4の度数分布とヒストグラム
wb_T4_count <- dplyr::count(data, wb_T4)
knitr::kable(wb_T4_count) #テーブル化
uuuu <- ggplot(data = data, mapping = aes(x = wb_T4, fill = factor(wb_T4))) + geom_histogram(binwidth = 0.5) #視覚化
ggplotly(uuuu) #視覚化

#ev_T1の度数分布とヒストグラム
ev_T1_count <- dplyr::count(data, ev_T1)
knitr::kable(ev_T1_count) #テーブル化
vvvv <- ggplot(data = data, mapping = aes(x = ev_T1, fill = factor(ev_T1))) + geom_histogram(binwidth = 0.5) #視覚化
ggplotly(vvvv) #視覚化

#ev_T2の度数分布とヒストグラム
ev_T2_count <- dplyr::count(data, ev_T2)
knitr::kable(ev_T2_count) #テーブル化
wwww <- ggplot(data = data, mapping = aes(x = ev_T2, fill = factor(ev_T2))) + geom_histogram(binwidth = 0.5) #視覚化
ggplotly(wwww) #視覚化

#ev_T3の度数分布とヒストグラム
ev_T3_count <- dplyr::count(data, ev_T3)
knitr::kable(ev_T3_count) #テーブル化
panda <- ggplot(data = data, mapping = aes(x = ev_T3, fill = factor(ev_T3))) + geom_histogram(binwidth = 0.5) #視覚化
ggplotly(panda) #視覚化

#ev_T4の度数分布とヒストグラム
ev_T4_count <- dplyr::count(data, ev_T4)
knitr::kable(ev_T4_count) #テーブル化
yyyy <- ggplot(data = data, mapping = aes(x = ev_T4, fill = factor(ev_T4))) + geom_histogram(binwidth = 0.5) #視覚化
ggplotly(yyyy) #視覚化

#hsc_onemonthの度数分布とヒストグラム
hsc_onemonth_count <- dplyr::count(data, hsc_onemonth)
knitr::kable(hsc_onemonth_count) #テーブル化
zzzz <- ggplot(data = data, mapping = aes(x = hsc_onemonth, fill = factor(hsc_onemonth))) + geom_histogram(binwidth = 0.3) + guides(fill = "none") #視覚化
ggplotly(zzzz) #視覚化

#wb_onemonthの度数分布とヒストグラム
wb_onemonth_count <- dplyr::count(data, wb_onemonth)
knitr::kable(wb_onemonth_count) #テーブル化
A <- ggplot(data = data, mapping = aes(x = wb_onemonth, fill = factor(wb_onemonth))) + geom_histogram(binwidth = 0.3) + guides(fill = "none") #視覚化
ggplotly(A) #視覚化

#ev_onemonthの度数分布とヒストグラム
ev_onemonth_count <- dplyr::count(data, ev_onemonth)
knitr::kable(ev_onemonth_count) #テーブル化
B <- ggplot(data = data, mapping = aes(x = ev_onemonth, fill = factor(ev_onemonth))) + geom_histogram(binwidth = 0.3) + guides(fill = "none") #視覚化
ggplotly(B) #視覚化
```

## 1-4. 記述統計量
```{r stats, include = TRUE}
#hsc_T1
hsc_T1_discriptive <- 
  data %>%
  drop_na() %>%
  dplyr::summarise(n = n (), #グループの人数を出力
                   hsc1.T1.mean = mean (hsc1_T1), #hsc1_T1の平均
                   hsc1.T1.sd = sd (hsc1_T1), #hsc1_T1のSD
                   hsc2.T1.mean = mean (hsc2_T1), 
                   hsc2.T1.sd = sd (hsc2_T1),
                   hsc3.T1.mean = mean (hsc3_T1), 
                   hsc3.T1.sd = sd (hsc3_T1),
                   hsc4.T1.mean = mean (hsc4_T1), 
                   hsc4.T1.sd = sd (hsc4_T1),
                   hsc5.T1.mean = mean (hsc5_T1), 
                   hsc5.T1.sd = sd (hsc5_T1),
                   hsc6.T1.mean = mean (hsc6_T1), 
                   hsc6.T1.sd = sd (hsc6_T1),
                   hsc7.T1.mean = mean (hsc7_T1), 
                   hsc7.T1.sd = sd (hsc7_T1),
                   hsc8.T1.mean = mean (hsc8_T1), 
                   hsc8.T1.sd = sd (hsc8_T1),
                   hsc9.T1.mean = mean (hsc9_T1), 
                   hsc9.T1.sd = sd (hsc9_T1),
                   hsc10.T1.mean = mean (hsc10_T1), 
                   hsc10.T1.sd = sd (hsc10_T1),
                   hsc11.T1.mean = mean (hsc11_T1), 
                   hsc11.T1.sd = sd (hsc11_T1),
                   hsc12.T1.mean = mean (hsc4_T1), 
                   hsc12.T1.sd = sd (hsc4_T1),
                   eoe.mean.T1 = mean (eoe_T1),
                   eoe.sd.T1 = sd (eoe_T1),
                   lst.mean.T1 = mean (lst_T1),
                   lst.sd.T1 = sd (lst_T1),
                   aes.mean.T1 = mean (aes_T1),
                   aes.sd.T1 = sd (aes_T1),
                   hsc.mean.T1 = mean (hsc_T1),
                   hsc.sd.T1 = sd (hsc_T1))
knitr::kable(hsc_T1_discriptive, digits = 2) #出力

#hsc_T2
hsc_T2_discriptive <- 
  data %>%
  drop_na() %>%
  dplyr::summarise(n = n (), #グループの人数を出力
                   hsc1.T2.mean = mean (hsc1_T2), #hsc1_T2の平均
                   hsc1.T2.sd = sd (hsc1_T2), #hsc1_T2のSD
                   hsc2.T2.mean = mean (hsc2_T2), 
                   hsc2.T2.sd = sd (hsc2_T2),
                   hsc3.T2.mean = mean (hsc3_T2), 
                   hsc3.T2.sd = sd (hsc3_T2),
                   hsc4.T2.mean = mean (hsc4_T2), 
                   hsc4.T2.sd = sd (hsc4_T2),
                   hsc5.T2.mean = mean (hsc5_T2), 
                   hsc5.T2.sd = sd (hsc5_T2),
                   hsc6.T2.mean = mean (hsc6_T2), 
                   hsc6.T2.sd = sd (hsc6_T2),
                   hsc7.T2.mean = mean (hsc7_T2), 
                   hsc7.T2.sd = sd (hsc7_T2),
                   hsc8.T2.mean = mean (hsc8_T2), 
                   hsc8.T2.sd = sd (hsc8_T2),
                   hsc9.T2.mean = mean (hsc9_T2), 
                   hsc9.T2.sd = sd (hsc9_T2),
                   hsc10.T2.mean = mean (hsc10_T2), 
                   hsc10.T2.sd = sd (hsc10_T2),
                   hsc11.T2.mean = mean (hsc11_T2), 
                   hsc11.T2.sd = sd (hsc11_T2),
                   hsc12.T2.mean = mean (hsc4_T2), 
                   hsc12.T2.sd = sd (hsc4_T2),
                   eoe.mean.T2 = mean (eoe_T2),
                   eoe.sd.T2 = sd (eoe_T2),
                   lst.mean.T2 = mean (lst_T2),
                   lst.sd.T2 = sd (lst_T2),
                   aes.mean.T2 = mean (aes_T2),
                   aes.sd.T2 = sd (aes_T2),
                   hsc.mean.T2 = mean (hsc_T2),
                   hsc.sd.T2 = sd (hsc_T2)) 
knitr::kable(hsc_T2_discriptive, digits = 2) #出力

#hsc_T3
hsc_T3_discriptive <- 
  data %>%
  drop_na() %>%
  dplyr::summarise(n = n (), #グループの人数を出力
                   hsc1.T3.mean = mean (hsc1_T3), #hsc1_T3の平均
                   hsc1.T3.sd = sd (hsc1_T3), #hsc1_T3のSD
                   hsc2.T3.mean = mean (hsc2_T3), 
                   hsc2.T3.sd = sd (hsc2_T3),
                   hsc3.T3.mean = mean (hsc3_T3), 
                   hsc3.T3.sd = sd (hsc3_T3),
                   hsc4.T3.mean = mean (hsc4_T3), 
                   hsc4.T3.sd = sd (hsc4_T3),
                   hsc5.T3.mean = mean (hsc5_T3), 
                   hsc5.T3.sd = sd (hsc5_T3),
                   hsc6.T3.mean = mean (hsc6_T3), 
                   hsc6.T3.sd = sd (hsc6_T3),
                   hsc7.T3.mean = mean (hsc7_T3), 
                   hsc7.T3.sd = sd (hsc7_T3),
                   hsc8.T3.mean = mean (hsc8_T3), 
                   hsc8.T3.sd = sd (hsc8_T3),
                   hsc9.T3.mean = mean (hsc9_T3), 
                   hsc9.T3.sd = sd (hsc9_T3),
                   hsc10.T3.mean = mean (hsc10_T3), 
                   hsc10.T3.sd = sd (hsc10_T3),
                   hsc11.T3.mean = mean (hsc11_T3), 
                   hsc11.T3.sd = sd (hsc11_T3),
                   hsc12.T3.mean = mean (hsc4_T3), 
                   hsc12.T3.sd = sd (hsc4_T3),
                   eoe.mean.T3 = mean (eoe_T3),
                   eoe.sd.T3 = sd (eoe_T3),
                   lst.mean.T3 = mean (lst_T3),
                   lst.sd.T3 = sd (lst_T3),
                   aes.mean.T3 = mean (aes_T3),
                   aes.sd.T3 = sd (aes_T3),
                   hsc.mean.T3 = mean (hsc_T3),
                   hsc.sd.T3 = sd (hsc_T3)) 
knitr::kable(hsc_T3_discriptive, digits = 2) #出力

#hsc_T4
hsc_T4_discriptive <- 
  data %>%
  drop_na() %>%
  dplyr::summarise(n = n (), #グループの人数を出力
                   hsc1.T4.mean = mean (hsc1_T4), #hsc1_T4の平均
                   hsc1.T4.sd = sd (hsc1_T4), #hsc1_T4のSD
                   hsc2.T4.mean = mean (hsc2_T4), 
                   hsc2.T4.sd = sd (hsc2_T4),
                   hsc3.T4.mean = mean (hsc3_T4), 
                   hsc3.T4.sd = sd (hsc3_T4),
                   hsc4.T4.mean = mean (hsc4_T4), 
                   hsc4.T4.sd = sd (hsc4_T4),
                   hsc5.T4.mean = mean (hsc5_T4), 
                   hsc5.T4.sd = sd (hsc5_T4),
                   hsc6.T4.mean = mean (hsc6_T4), 
                   hsc6.T4.sd = sd (hsc6_T4),
                   hsc7.T4.mean = mean (hsc7_T4), 
                   hsc7.T4.sd = sd (hsc7_T4),
                   hsc8.T4.mean = mean (hsc8_T4), 
                   hsc8.T4.sd = sd (hsc8_T4),
                   hsc9.T4.mean = mean (hsc9_T4), 
                   hsc9.T4.sd = sd (hsc9_T4),
                   hsc10.T4.mean = mean (hsc10_T4), 
                   hsc10.T4.sd = sd (hsc10_T4),
                   hsc11.T4.mean = mean (hsc11_T4), 
                   hsc11.T4.sd = sd (hsc11_T4),
                   hsc12.T4.mean = mean (hsc4_T4), 
                   hsc12.T4.sd = sd (hsc4_T4),
                   eoe.mean.T4 = mean (eoe_T4),
                   eoe.sd.T4 = sd (eoe_T4),
                   lst.mean.T4 = mean (lst_T4),
                   lst.sd.T4 = sd (lst_T4),
                   aes.mean.T4 = mean (aes_T4),
                   aes.sd.T4 = sd (aes_T4),
                   hsc.mean.T4 = mean (hsc_T4),
                   hsc.sd.T4 = sd (hsc_T4)) 
knitr::kable(hsc_T4_discriptive, digits = 2) #出力

#hsc_onemonth
hsc_onemonth_discriptive <- 
  data %>%
  drop_na() %>%
  dplyr::summarise(n = n (), #グループの人数を出力
                   hsc1.onemonth.mean = mean (hsc_onemonth), #hsc_onemonthの平均
                   hsc1.onemonth.sd = sd (hsc_onemonth)) #hsc_onemonthのSD
knitr::kable(hsc_onemonth_discriptive, digits = 2) #出力

#wb_T1
wb_T1_discriptive <- 
  data %>%
  drop_na() %>%
  dplyr::summarise(n = n (), #グループの人数を出力
                   wb1.T1.mean = mean (wb1_T1), #hsc1_T10の平均
                   wb1.T1.sd = sd (wb1_T1), #hsc1_T10のSD
                   wb2.T1.mean = mean (wb2_T1), 
                   wb2.T1.sd = sd (wb2_T1),
                   wb3.T1.mean = mean (wb3_T1), 
                   wb3.T1.sd = sd (wb3_T1),
                   wb4.T1.mean = mean (wb4_T1), 
                   wb4.T1.sd = sd (wb4_T1),
                   wb5.T1.mean = mean (wb5_T1), 
                   wb5.T1.sd = sd (wb5_T1),
                   wb.T1.mean = mean (wb_T1),
                   wb.T1.sd = sd (wb_T1))
knitr::kable(wb_T1_discriptive, digits = 2) #出力

#wb_T2
wb_T2_discriptive <- 
  data %>%
  drop_na() %>%
  dplyr::summarise(n = n (), #グループの人数を出力
                   wb1.T2.mean = mean (wb1_T2), #hsc1_T2の平均
                   wb1.T2.sd = sd (wb1_T2), #hsc1_T2のSD
                   wb2.T2.mean = mean (wb2_T2), 
                   wb2.T2.sd = sd (wb2_T2),
                   wb3.T2.mean = mean (wb3_T2), 
                   wb3.T2.sd = sd (wb3_T2),
                   wb4.T2.mean = mean (wb4_T2), 
                   wb4.T2.sd = sd (wb4_T2),
                   wb5.T2.mean = mean (wb5_T2), 
                   wb5.T2.sd = sd (wb5_T2),
                   wb.T2.mean = mean (wb_T2),
                   wb.T2.sd = sd (wb_T2))
knitr::kable(wb_T2_discriptive, digits = 2) #出力

#wb_T3
wb_T3_discriptive <- 
  data %>%
  drop_na() %>%
  dplyr::summarise(n = n (), #グループの人数を出力
                   wb1.T3.mean = mean (wb1_T3), #hsc1_T3の平均
                   wb1.T3.sd = sd (wb1_T3), #hsc1_T3のSD
                   wb2.T3.mean = mean (wb2_T3), 
                   wb2.T3.sd = sd (wb2_T3),
                   wb3.T3.mean = mean (wb3_T3), 
                   wb3.T3.sd = sd (wb3_T3),
                   wb4.T3.mean = mean (wb4_T3), 
                   wb4.T3.sd = sd (wb4_T3),
                   wb5.T3.mean = mean (wb5_T3), 
                   wb5.T3.sd = sd (wb5_T3),
                   wb.T3.mean = mean (wb_T3),
                   wb.T3.sd = sd (wb_T3))
knitr::kable(wb_T3_discriptive, digits = 2) #出力

#wb_T4
wb_T4_discriptive <- 
  data %>%
  drop_na() %>%
  dplyr::summarise(n = n (), #グループの人数を出力
                   wb1.T4.mean = mean (wb1_T4), #hsc1_T4の平均
                   wb1.T4.sd = sd (wb1_T4), #hsc1_T4のSD
                   wb2.T4.mean = mean (wb2_T4), 
                   wb2.T4.sd = sd (wb2_T4),
                   wb3.T4.mean = mean (wb3_T4), 
                   wb3.T4.sd = sd (wb3_T4),
                   wb4.T4.mean = mean (wb4_T4), 
                   wb4.T4.sd = sd (wb4_T4),
                   wb5.T4.mean = mean (wb5_T4), 
                   wb5.T4.sd = sd (wb5_T4),
                   wb.T4.mean = mean (wb_T4),
                   wb.T4.sd = sd (wb_T4))
knitr::kable(wb_T4_discriptive, digits = 2) #出力

#wb_onemonth
wb_onemonth_discriptive <- 
  data %>%
  drop_na() %>%
  dplyr::summarise(n = n (), #グループの人数を出力
                   wb.onemonth.mean = mean (wb_onemonth), #wb_onemonthの平均
                   wb.onemonth.sd = sd (wb_onemonth)) #wb_onemonthのSD
knitr::kable(wb_onemonth_discriptive, digits = 2) #出力

#ev_T1
ev_T1_discriptive <- 
  data %>%
  drop_na() %>%
  dplyr::summarise(n = n (), #グループの人数を出力
                   ev1.T1.mean = mean (ev1_T1), #ev1_T1の平均
                   ev1.T1.sd = sd (ev1_T1), #ev1_T1のSD
                   ev2.T1.mean = mean (ev2_T1), 
                   ev2.T1.sd = sd (ev2_T1),
                   ev.T1.mean = mean (ev_T1),
                   ev.T1.sd = sd (ev_T1))
knitr::kable(ev_T1_discriptive, digits = 2) #出力

#ev_T2
ev_T2_discriptive <- 
  data %>%
  drop_na() %>%
  dplyr::summarise(n = n (), #グループの人数を出力
                   ev1.T2.mean = mean (ev1_T2), #ev1_T2の平均
                   ev1.T2.sd = sd (ev1_T2), #ev1_T2のSD
                   ev2.T2.mean = mean (ev2_T2), 
                   ev2.T2.sd = sd (ev2_T2),
                   ev.T2.mean = mean (ev_T2),
                   ev.T2.sd = sd (ev_T2))
knitr::kable(ev_T2_discriptive, digits = 2) #出力

#ev_T3
ev_T3_discriptive <- 
  data %>%
  drop_na() %>%
  dplyr::summarise(n = n (), #グループの人数を出力
                   ev1.T3.mean = mean (ev_T3), #ev1_T3の平均
                   ev1.T3.sd = sd (ev1_T3), #ev1_T3のSD
                   ev2.T3.mean = mean (ev2_T3), 
                   ev2.T3.sd = sd (ev2_T3),
                   ev.T3.mean = mean (ev_T3),
                   ev.T3.sd = sd (ev_T3))
knitr::kable(ev_T3_discriptive, digits = 2) #出力

#ev_T4
ev_T4_discriptive <- 
  data %>%
  drop_na() %>%
  dplyr::summarise(n = n (), #グループの人数を出力
                   ev1.T4.mean = mean (ev1_T4), #ev1_T4の平均
                   ev1.T4.sd = sd (ev1_T4), #ev1_T4のSD
                   ev2.T4.mean = mean (ev2_T4), 
                   ev2.T4.sd = sd (ev2_T4),
                   ev.T4.mean = mean (ev_T4),
                   ev.T4.sd = sd (ev_T4))
knitr::kable(ev_T4_discriptive, digits = 2) #出力

#ev_onemonth
ev_onemonth_discriptive <- 
  data %>%
  drop_na() %>%
  dplyr::summarise(n = n (), #グループの人数を出力
                   ev.onemonth.mean = mean (ev_onemonth), #ev_onemonthの平均
                   ev.onemonth.sd = sd (ev_onemonth)) #ev_onemonthのSD
knitr::kable(ev_onemonth_discriptive, digits = 2) #出力

#age_T1
age_T1_discriptive <- 
  data %>%
  drop_na() %>%
  dplyr::summarise(n = n (), #グループの人数を出力
                   age.T1.mean = mean (age_T1), #age_T1の平均
                   age.T1.sd = sd (age_T1)) #age_T1のSD
knitr::kable(age_T1_discriptive, digits = 2) #出力

#age_T2
age_T2_discriptive <- 
  data %>%
  drop_na() %>%
  dplyr::summarise(n = n (), #グループの人数を出力
                   age.T2.mean = mean (age_T2), #age_T2の平均
                   age.T2.sd = sd (age_T2)) #age_T2のSD
knitr::kable(age_T2_discriptive, digits = 2) #出力

#age_T3
age_T3_discriptive <- 
  data %>%
  drop_na() %>%
  dplyr::summarise(n = n (), #グループの人数を出力
                   age.T3.mean = mean (age_T3), #age_T3の平均
                   age.T3.sd = sd (age_T3)) #age_T3のSD
knitr::kable(age_T3_discriptive, digits = 2) #出力

#age_T4
age_T4_discriptive <- 
  data %>%
  drop_na() %>%
  dplyr::summarise(n = n (), #グループの人数を出力
                   age.T4.mean = mean (age_T4), #age_T4の平均
                   age.T4.sd = sd (age_T4)) #age_T4のSD
knitr::kable(age_T4_discriptive, digits = 2) #出力
```

## 1-5. 内的整合性
```{r consistency, include = TRUE}
library(psych)
library(GPArotation)

#hsc_T1
alpha(data[, c(6,7,8,9,11,12,13,14,15,16,17)]) #alpha .63
omega(data[, c(6,7,8,9,11,12,13,14,15,16,17)],3,fm="ml") #omega hierarchical=.41, omega total=.74

#hsc_T2
alpha(data[, c(27,28,29,30,32,33,34,35,36,37,38)]) #alpha .78
omega(data[, c(27,28,29,30,32,33,34,35,36,37,38)],3,fm="ml") #omega hierarchical=.64, omega total=.84

#hsc_T3
alpha(data[, c(48,49,50,51,53,54,55,56,57,58,59)]) #alpha .75
omega(data[, c(48,49,50,51,53,54,55,56,57,58,59)],3,fm="ml") #omega hierarchical=.59, omega total=.83

#hsc_T4
alpha(data[, c(69,70,71,72,74,75,76,77,78,79,80)]) #alpha .79
omega(data[, c(69,70,71,72,74,75,76,77,78,79,80)],3,fm="ml") #omega hierarchical=.71, omega total=.86

#wb_T1
alpha(data[, c(18:22)]) #alpha .78
omega(data[, c(18:22)],1,fm="ml") #omega hierarchical=.78, omega total=.79

#wb_T2
alpha(data[, c(39:43)]) #alpha .85
omega(data[, c(39:43)],1,fm="ml") #omega hierarchical=.83, omega total=.85

#wb_T3
alpha(data[, c(60:64)]) #alpha .85
omega(data[, c(60:64)],1,fm="ml") #omega hierarchical=.85, omega total=.85

#wb_T4
alpha(data[, c(81:85)]) #alpha .90
omega(data[, c(81:85)],1,fm="ml") #omega hierarchical=.90, omega total=.90
```

# （2）相関係数の算出
```{r corheatmap, include = TRUE}
cordata <- data %>% dplyr::select(hsc_T1,hsc_T2,hsc_T3,hsc_T4,wb_T1,wb_T2,wb_T3,wb_T4,ev_T1,ev_T2,ev_T3,ev_T4,hsc_onemonth,wb_onemonth,ev_onemonth) %>% drop_na()
head(cordata)
names(cordata)
cormat <- round(cor(cordata),2)
head(cormat)
library(reshape2)
melted_cormat <- melt(cormat)
head(melted_cormat)
ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
  geom_tile(color = "white")+
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0, limit = c(-1,1), space = "Lab", 
                       name="Pearson\nCorrelation") +
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, 
                                   size = 12, hjust = 1))+
  coord_fixed()
```

# 分析は以上です